---
copyright: Copyright &copy; 2017-2021 Mark Cornick
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Contributing: contributing.md
repo_name: markcornick/linenoise-classic
repo_url: https://github.com/markcornick/linenoise-classic/
site_author: Mark Cornick
site_description: Generates strings that can be used as reasonably secure passwords
site_name: linenoise-classic
theme:
  name: readthedocs
