---
name: mkdocs
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install git+https://${GH_PAT}@github.com/squidfunk/mkdocs-material-insiders.git mkdocs-git-revision-date-localized-plugin mkdocs-minify-plugin
      - run: mkdocs gh-deploy --force
env:
  GH_PAT: ${{ secrets.GH_PAT }}
